export enum DomainEventName {
  ORDER_RESERVED = "ORDER_RESERVED",
  ORDER_PAID = "ORDER_PAID",
  TICKETS_ISSUED = "TICKETS_ISSUED",
  TICKET_CHECKED_IN = "TICKET_CHECKED_IN",
  ORDER_CONFIRMATION_EMAIL_SENT = "ORDER_CONFIRMATION_EMAIL_SENT",
  ORDER_EXPIRED = "ORDER_EXPIRED",
  INVENTORY_RESERVATION_RELEASED = "INVENTORY_RESERVATION_RELEASED",
  RESERVATION_EXPIRED = "RESERVATION_EXPIRED",
  INVENTORY_RELEASED = "INVENTORY_RELEASED",
  LATE_PAYMENT_DETECTED = "LATE_PAYMENT_DETECTED",
  LATE_PAYMENT_CASE_CREATED = "LATE_PAYMENT_CASE_CREATED",
  LATE_PAYMENT_CASE_RESOLVED = "LATE_PAYMENT_CASE_RESOLVED",
  PAYMENT_RECONCILED_PAID = "PAYMENT_RECONCILED_PAID",
  PAYMENT_RECONCILED_FAILED = "PAYMENT_RECONCILED_FAILED",
  MANUAL_OVERRIDE_EXECUTED = "MANUAL_OVERRIDE_EXECUTED"
}

export const DOMAIN_EVENT_NAMES = Object.values(DomainEventName);
